services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\MastermindContext\Domain\Game\GameRepositoryInterface:
        class: App\MastermindContext\Infrastructure\Game\Persistence\Repository\DoctrineGameRepository

    App\MastermindContext\Infrastructure\Game\Http\:
        resource: '../../Http/*Controller.php'
        tags:
            - {name: controller.service_arguments}

    App\MastermindContext\Application\Game\Command\:
        resource: '../../../../Application/Game/Command/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: command.bus }

    App\MastermindContext\Application\Game\Query\:
        resource: '../../../../Application/Game/Query/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: query.bus }

    App\MastermindContext\Domain\Game\Service\:
        resource: '../../../../Domain/Game/Service'

    App\MastermindContext\Infrastructure\Game\Validator\:
        resource: '../../Validator/'

