services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\MastermindContext\Domain\Game\GameRepositoryInterface:
        class: App\MastermindContext\Infrastructure\Game\Persistence\Repository\DoctrineGameRepository
