doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            game_id: App\MastermindContext\Infrastructure\Game\Persistence\Type\GameIdType
            game_status: App\MastermindContext\Infrastructure\Game\Persistence\Type\GameStatusType
            color_code: App\MastermindContext\Infrastructure\ColorCode\Persistence\Type\ColorCodeType
            guess_id: App\MastermindContext\Infrastructure\Guess\Persistence\Type\GuessIdType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\MastermindContext\Domain\Game\Game:
                type: xml
                dir: '%kernel.project_dir%/src/MastermindContext/Infrastructure/Game/Persistence/Mapping'
                is_bundle: false
                prefix: App\MastermindContext\Domain\Game
            App\MastermindContext\Domain\Guess\Guess:
                type: xml
                dir: '%kernel.project_dir%/src/MastermindContext/Infrastructure/Guess/Persistence/Mapping'
                is_bundle: false
                prefix: App\MastermindContext\Domain\Guess

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
