version: "3.6"

services:
    nginx:
        image: nginx:1.23.3
        ports:
            - "80:80"
        volumes:
            - .:/app
            - ./infra/nginx/config.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    php:
        build:
            context: ./infra/php
        ports:
            - "9000:9000"
        volumes:
            - .:/app
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3333"
        env_file:
            - ./infra/mysql/.env.mysql
