services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Shared\Domain\Command\CommandBusInterface:
        class: App\Shared\Infrastructure\Command\SymfonyMessengerCommandBus

    App\Shared\Domain\Query\QueryBusInterface:
        class: App\Shared\Infrastructure\Query\SymfonyMessengerQueryBus

    App\Shared\Infrastructure\EventListener\ExceptionEventListener:
        tags: [kernel.event_listener]

