services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\MastermindContext\Infrastructure\Guess\Http\:
        resource: '../../Http/*Controller.php'
        tags:
            - {name: controller.service_arguments}

    App\MastermindContext\Application\Guess\Command\:
        resource: '../../../../Application/Guess/Command/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: command.bus }

